### ISSUE TITLE
Define Labels

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#1]

**Comment by asi345** [comment]
Creating priority labels(High, Medium, Low)

**Comment by CodeBlo** [comment]
From what I've seen through my internship and the older repositories in [bounswe](https://github.com/bounswe) repo.
Type of the issue:
Type: 
- Bug
- Task
- New Feature
- Documentation
Status of the issue,
Status:
- To Do
- In Progress
- Done
- Cancelled

May be a label for the duplicate issues. Like "Duplicate".

**Comment by onurcanavci** [comment]
We can add labels according to subjects like `Wiki`, `ReadMe`

**Comment by CodeBlo** [comment]
Labels are created and issue is done.
