### ISSUE TITLE
Migrate from DynamoDB to MongoDB

### ISSUE THREAD

**Issue by asi345** [bounswe/2021SpringGroup7#102]
We changed our database choice to MongoDB, the code will be updated according to it

**Comment by asi345** [comment]
I changed the docker images and the code integration of the flask for database to completely use mongoDB. It is now ready and waiting for review.

**Comment by kocasariumut** [comment]
It works as intended.

**Comment by mrabiabrn** [comment]
Runned in my local and it works properly, closing the issue.
