### ISSUE TITLE
Creating Personal Wiki Pages

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#12]
Creating the personal  page in wiki.

- [x] [Abdulkadir Elmacı](https://github.com/bounswe/2021SpringGroup7/wiki/Abdulkadir-Elmacı)
- [x] [Efe Şabanoğlu]()
- [x] [Erencan Uysal](https://github.com/bounswe/2021SpringGroup7/wiki/Erencan-Uysal)
- [x] [Hamza Akyıldız](https://github.com/bounswe/2021SpringGroup7/wiki/Hamza-Akyıldız)
- [x] [İsmail Ata İnan](https://github.com/bounswe/2021SpringGroup7/wiki/İsmail-Ata-İnan)
- [x] [Merve Rabia Barın](https://github.com/bounswe/2021SpringGroup7/wiki/Merve-Rabia-Barın)
- [x] [Onur Can Avcı](https://github.com/bounswe/2021SpringGroup7/wiki/Onur-Can-Avcı)
- [x] [Ramazan Bulut](https://github.com/bounswe/2021SpringGroup7/wiki/Ramazan-Bulut)
- [x] [Umut Kocasarı](https://github.com/bounswe/2021SpringGroup7/wiki/Umut-Kocasarı)

**Comment by CodeBlo** [comment]
I created my own page.

**Comment by asi345** [comment]
I finished my personal page customization.

**Comment by mrabiabrn** [comment]
I created & edited my personal page

**Comment by hamzaakyildiz** [comment]
I created my personal wiki page

**Comment by erencanuysal** [comment]
I edited my personal page.

**Comment by onurcanavci** [comment]
I created my personal wiki page

**Comment by efesabanogluu** [comment]
Finally, I editted my page.
