### ISSUE TITLE
Create Wiki Home page

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#16]
Creating Wiki Home page

**Comment by asi345** [comment]
Added general information about the group and task. Listed all team members with adding link to their personal wiki pages. Created communication plan, favorite GitHub repositories and research about Git sections and wrote some short explanations about them. Also for each of these sections, I added links to their relevant Wiki pages. Thus, all of our Wiki pages are easily accessible from home wiki page.

**Comment by asi345** [comment]
I added all the necessary links and explanation that can be written this week. But each week, it should be updated to show our weekly meeting notes, research, work and anything that is worth showing in our repository.
