### ISSUE TITLE
CB-38 Bugfix/Fixing The Docker Configs For Frontend, CORS Error For Backend and Follow Action Bug

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#215]
* There was some bugs using the installed yarn package serve. It didn't load the static files produced from react. 
* There was a trailing / at the end of home api. Frontend sends a request the "/api/home" so the flask automatically redirects it to the "/api/home/" and it returns 308 to frontend. This produces an CORS error in frontend.
* The follow action when user is visible, instead of the username the user object pulled from the mongo is added. Needs to be fixed

**Comment by CodeBlo** [comment]
I pushed some of the changes needed to be done to CB-38 branch.

**Comment by onurcanavci** [comment]
I fixed some of problems and missing features in frontend

**Comment by onurcanavci** [comment]
Fixed some problems in frontend and backend. You can see changees in https://github.com/bounswe/2021SpringGroup7/pull/219
