### ISSUE TITLE
Research platforms similar to our projects 

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#22]
Researching  mobile applications and web applications which similars to our projects assigned us

**Comment by onurcanavci** [comment]
I'm thinking to research Swarm and Instagram features

**Comment by efesabanogluu** [comment]
Then I will be dealing with Foursquare and Facebook.

**Comment by onurcanavci** [comment]
I will search StoryPlace

**Comment by onurcanavci** [comment]
We finished the task and you can review our wiki page .If there is a place we forgot or something you want to add please creating a new issue and assign to us.

Wiki page link: https://github.com/bounswe/2021SpringGroup7/wiki/Research-Similar-Projects
