### ISSUE TITLE
Distribution of tasks for Front-end Back-end and Mobile

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#231]
We should revise our project plan and distribute tasks for this semester.

**Comment by ramazanbulut** [comment]
I also prefer Mobile Development.

**Comment by ramazanbulut** [comment]
Back-End: Python Django
Front-End: React
Mobile: React Native

**Comment by efesabanogluu** [comment]
I better work on the backend of the app. Everyone seems to have made their preferences.
