### ISSUE TITLE
Preparing Issue Template for Wiki Related Issues

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#237]
It would be better if we have an issue template for Wiki page-related tasks. The template should satisfy the conditions below: 

* A clear task description for the title
* Statement of what will be done
* Brief of what have been done

**Comment by kocasariumut** [comment]
Issue template for wiki is added to repository. The template could be found here: https://github.com/bounswe/2021SpringGroup7/blob/master/.github/ISSUE_TEMPLATE/wiki.md
