### ISSUE TITLE
Adding Error Handling Cases to Sequence Diagrams

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#240]
There is missing error handling cases in Sequence Diagrams. The diagrams below should be updated accordingly :
* [Edit Profile Information](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams#3-edit-profile-information)

**Comment by CodeBlo** [comment]
Changed the given sequence diagram to below:
![image](https://user-images.githubusercontent.com/55738066/139703947-77d33d00-186f-4ca1-aac3-16548e4d9b6c.png)
Waiting for review

**Comment by mrabiabrn** [comment]
It seems to provide necessary changes. I am closing the issue.
