### ISSUE TITLE
Add Parameters to Parameterless Functions in Class and Sequence Diagrams

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#241]
- Some class diagram functions does not have any parameters. These functions should be changed in class diagrams.
- The added parameters should also be changed in sequence diagrams.
- The addition of parameters also changes some of the logical sequences. The logic should be changed according to newly added parameters.

**Comment by mrabiabrn** [comment]
It seems ok. I am closing the issue.

**Comment by erencanuysal** [comment]
We rewieved and make some changes on class diagram. You can see it from [here](https://github.com/bounswe/2021SpringGroup7/wiki/Class-Diagram)
