### ISSUE TITLE
Preparing Template for Pull Requests

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#242]
We should prepare a PR template to ensure simplicity and intelligibility. There are some templates on internet. We should pay attention to:

* What is the change?
* What does it fix?
* Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
* How has it been tested?
- Reference : https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/

**Comment by kocasariumut** [comment]
Pull request template is added to repository. The template could be found here: https://github.com/bounswe/2021SpringGroup7/blob/master/.github/pull_request_template.md
