### ISSUE TITLE
Add Error Handling Cases to DB (Sequence Diagrams)

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#244]
There are missing error handling cases in Sequence Diagrams DB. 

The diagram should be updated accordingly :  [Edit Profile Information](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams#3-edit-profile-information)

**Comment by mrabiabrn** [comment]
* Converted the shape of the DB to cylinder & removed the rectangles from DB's line in Sequence Diagram 1, 2, 4, 5, 7, 8, 9, 10, 11, 12.

You can access and review the changes from the Sequence Diagram LucidChart link shared on Slack.

**Comment by CodeBlo** [comment]
Checked the changed diagrams in Lucid Chart. Seems good. They need to be updated in the Wiki. @mrabiabrn 
[Sequence Diagram Wiki Page](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams)

**Comment by mrabiabrn** [comment]
This issue has been handled. Please, refer #250 for uploading Sequence Diagrams to Wiki page.
