### ISSUE TITLE
[WIKI UPDATE] Requirements update for final version 

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#249]
Why is this wiki update necessary, what is the problem?
--------------------------------------

The actor of the requirement 1.1.1.2 is not the user
The requirement 1.1.1.3 includes multiple action in one statement
The requirement1.1.2.6 includes multiple action in one statement

Describe the solution you'd like
--------------------------------

The requirement 1.1.1.2 should be move to the system requirement or deleted if necessary
The requirement 1.1.1.3 should be separated into multiple requirements
The requirement1.1.2.6 should be separated into multiple requirements

Additional context and references
---------------------------------

None

**Comment by hamzaakyildiz** [comment]
Necessary adjustments are made. @kocasariumut

**Comment by kocasariumut** [comment]
Requirements reviewed. There were 3 problems to be solved, described above. They have been solved and updated. Statements with multiple actions are correct now and also minor syntactic adjustments have been made. Requirements are more clear now.
The details could be found in the link: https://github.com/bounswe/2021SpringGroup7/wiki/Requirements
