### ISSUE TITLE
Upload Updated Sequence Diagrams to Wiki

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#250]
Sequence Diagrams have been updated in #240 and #244. However, the older version is present in our Wikipage.

 * Upload the modified version of Sequence Diagrams to [here](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams)

**Comment by CodeBlo** [comment]
I uploaded the [3rd sequence diagram edit profile information](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams#3-edit-profile-information)  with the [new version](https://github.com/bounswe/2021SpringGroup7/blob/master/Sequence%20Diagrams/Sequence%20Diagram%203.png)

**Comment by mrabiabrn** [comment]
I also updated other diagrams. Changes can be found in [here](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams).

**Comment by mrabiabrn** [comment]
Issue is handled
