### ISSUE TITLE
[WIKI UPDATE] Upload Updated Class Diagram to Wiki

### ISSUE THREAD

**Issue by ramazanbulut** [bounswe/2021SpringGroup7#251]
Why is this wiki update necessary, what is the problem?
--------------------------------------

Updated Class Diagram should be uploaded to wiki page of repository

Describe the solution you'd like
--------------------------------

Uploading PNG format image of class diagram

Additional context and references
---------------------------------

https://user-images.githubusercontent.com/56506578/139820973-a49cd204-5634-4801-894e-5256784baf24.png

**Comment by mrabiabrn** [comment]
New version is present in https://github.com/bounswe/2021SpringGroup7/wiki/Class-Diagram. I am closing the issue.
