### ISSUE TITLE
Create Directory for Columbus Project

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#252]
A directory where we push our codes for Columbus Project is needed. 
- [x] Open a directory in [master](https://github.com/bounswe/2021SpringGroup7/tree/master) branch
- [x] Name directory as **Columbus**
- [x] Create *backend*, *frontend* and *mobile* directories under **Columbus**

**Comment by hamzaakyildiz** [comment]
Everything is done accordingly in [Columbus](https://github.com/bounswe/2021SpringGroup7/tree/master/Columbus)
