### ISSUE TITLE
Project Kickoff for Frontend

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#253]
- [x] Frontend project should be initialised.
- [x] The project starter files should e added.
- [x]  A dummy page for testing should be added.

**Comment by mrabiabrn** [comment]
We gathered for frontend tasks w\ @CodeBlo & @erencanuysal.
* Made sure that everyone installed npm & virtual env
* Initialized a react project
* Sent request to a public API and made sure that it is working
* Created a Dockerfile and tested docker build and run commands
* Pushed our starter project to [kickoff-frontend-253](https://github.com/bounswe/2021SpringGroup7/tree/kickoff-frontend-%23253)
