### ISSUE TITLE
Project Kickoff for Backend 

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#254]
- [x] Backend infrastructure will be set up. 

- [x] A Simple test API will be designed for frontend connection. 

- [x] Database connection will be set. 

- [ ] Backend will be deployed to the AWS instance.

**Comment by hamzaakyildiz** [comment]
[Backend](https://github.com/bounswe/2021SpringGroup7/tree/kickoff-backend) is implemented with necessary requirements listed above.

**Comment by efesabanogluu** [comment]
- [ ] Database infrastructure will be changed from MongoDb to PostgreSql.

**Comment by hamzaakyildiz** [comment]
Database infrastructure is changed to PosgreSql. Two port is added at 8000:/ and 8000:/test/hello/<str:name> for database and backend connection and also for frontend test connection. (@CodeBlo FYI) 
Success message at 8000:/  'Django has started. Go to /test/hello/{your_name}'
Success message at 8000:/test/hello/<str:name> '{your_name}' is succesfully tested the DB connection'
