### ISSUE TITLE
CM-1 Project Kickoff for Mobile

### ISSUE THREAD

**Issue by ramazanbulut** [bounswe/2021SpringGroup7#255]
we need to create a new React Native starter project for Columbus.
- [x] Mobile project should be initialised.
- [x] The project starter files should e added.
- [x]  A dummy view (probably login page and main page) for testing should be added.

**Comment by ramazanbulut** [comment]
branch can be found here [CM-1](https://github.com/bounswe/2021SpringGroup7/tree/CM-1)

**Comment by onurcanavci** [comment]
You can find the pull request at the right sidebar (linked pull request section).
