### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by kocasariumut** [bounswe/2021SpringGroup7#257]
- [x] An account should be created for Docker Hub
- [x] Github actions should be used to produce and push docker images to the Docker Hub Registry
- [x] Connection with the EC2 instance should be established with ssh and backend mobile should be updated
- [ ] All the processes should be tested and validated

**Comment by CodeBlo** [comment]
Additionally we might need to create a docker compose file for deployment

**Comment by CodeBlo** [comment]
ColumbusGroup7 account in docker hub: https://hub.docker.com/u/columbusgroup7

**Comment by CodeBlo** [comment]
The pipeline is working. It might need additional checking @kocasariumut

**Comment by kocasariumut** [comment]
The final pipeline is ready. It could be found in: https://github.com/bounswe/2021SpringGroup7/blob/master/.github/workflows/docker-publish.yml
