### ISSUE TITLE
Meeting #3 Notes

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#26]
Taking the notes of the Meeting#3 and writing it to wiki page.

**Comment by hamzaakyildiz** [comment]
I uploaded third meeting notes. I will close the issue unless you have comments

**Comment by mrabiabrn** [comment]
I have looked at it, it seems to cover everything we had discussed. Nothing to add.

**Comment by CodeBlo** [comment]
I also checked it. There is nothing to add. Closing.
