### ISSUE TITLE
Call API Written by Backend to Frontend 

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#264]
We need to test backend & frontend connection. A dummy API is written by backend team.
- Send request to "https://localhost:8000/test/hello/{input}" from frontend
- Check if it is successfully fetches

**Comment by CodeBlo** [comment]
After deploying to the instance we found a bug that use effect function run continuously. Should fix this
![image](https://user-images.githubusercontent.com/55738066/141178167-2f70e1f7-de1d-451a-93f0-d261fac19776.png)

**Comment by mrabiabrn** [comment]
Please, refer to the related [PR](https://github.com/bounswe/2021SpringGroup7/pull/277) for fixings.

**Comment by CodeBlo** [comment]
Problem is still ongoing.

**Comment by CodeBlo** [comment]
This is fixed. Closing.
