### ISSUE TITLE
Determining the requirements

### ISSUE THREAD

**Issue by efesabanogluu** [bounswe/2021SpringGroup7#27]
Specify the requirements and document them.

**Comment by asi345** [comment]
We documented the requirements in a Google Doc file to work on it together at the same time. The documentation should be formatted to a Markdown file, and then it should be uploaded to our Requirements Wiki Page.

**Comment by asi345** [comment]
After meeting whole group, we listed the mistakes and missing titles in Google Docs, we need to fix the Requirements page until tomorrow night.

**Comment by asi345** [comment]
We finalized all the requirements that we decided on. It is up to change in upcoming weeks but its first prototype is ready. Also, the mistakes that we encountered at the meeting is corrected. The Requirements page can be accessed from [here](https://github.com/bounswe/2021SpringGroup7/wiki/Requirements)
