### ISSUE TITLE
CF-2 Register Action Implementation In Frontend

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#271]
Is your proposal related to a problem?
--------------------------------------

The register page for the frontend should be implemented. Should be connected to our backend

--------------------------------

 The user should register in a secure manner with her password, username and email.

**Comment by erencanuysal** [comment]
I have created register dialog screen. And we also create main login page screen. You can see it from [here](https://github.com/bounswe/2021SpringGroup7/tree/development/Columbus/frontend/src/pages/Register).
