### ISSUE TITLE
 CF-1  Create Login Page 

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#272]
Is your proposal related to a problem?
--------------------------------------

Users of the Columbus need to enter their account.

Describe the solution you'd like
--------------------------------

- Login page should be created.
- Design should follow the Mockup conventions.

Describe alternatives you've considered
---------------------------------------

-

Additional context
------------------

-

**Comment by CodeBlo** [comment]
Closing. PR is merged.
