### ISSUE TITLE
CF-3 Footer Header and Navigation Bar

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#273]
Is your proposal related to a problem?
--------------------------------------

Footer, header and navigation bar should be arranged for the frontend part.

**Comment by mrabiabrn** [comment]
- I arranged the footer, added Columbus logo. Changes can be seen in [here](https://github.com/bounswe/2021SpringGroup7/tree/master/Columbus/frontend/src/components/Footer)
- I modified Header and put NavBar into header. Changes can be seen in [here](https://github.com/bounswe/2021SpringGroup7/tree/master/Columbus/frontend/src/components/Header)

**Comment by mrabiabrn** [comment]
@erencanuysal and @CodeBlo reviewed the changes in our frontend meeting.
For further info, look at the related [PR](https://github.com/bounswe/2021SpringGroup7/pull/283).
Issue has been handled.
