### ISSUE TITLE
Mail to teaching assistant for clarification

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#28]
There are some points which are not clear. We can add comments under this issue.

**Comment by onurcanavci** [comment]
Should we add milestone to all issues? If yes, what kind of milestone can we open in a task like extracting meeting notes?

**Comment by erencanuysal** [comment]
How should we document questions. Will there be a meeting with the customer?

**Comment by onurcanavci** [comment]
How can we create sub-issues of the main issue we have created?

**Comment by asi345** [comment]
I sent an email containing all of our questions.

**Comment by asi345** [comment]
I wrote the assistant's answers on Slack. It can be read there.
