### ISSUE TITLE
06.04.2021 meeting notes

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#31]
Document this meeting notes.

**Comment by erencanuysal** [comment]
I uploaded meeting notes.

**Comment by mrabiabrn** [comment]
I have reviewed it, it seems "request" written instead of "requirements" in the second line of Agenda part.
https://github.com/bounswe/2021SpringGroup7/wiki/Meeting-%234-(06.04.2021)#clipboard-agenda-
Other than that, I have nothing to add.

**Comment by erencanuysal** [comment]
I'm fixing now. Thanks!
