### ISSUE TITLE
Writing Exclusive Summary

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#316]
We should write exclusive summary for Milestone-1 Report. It should contain summary of project status and any changes that are planned for moving forward.

**Comment by CodeBlo** [comment]
We wrote the exclusive summary.Waiting for the group to review the changes

**Comment by erencanuysal** [comment]
We finished exclusive summary and submitted Milestone-1 report.  You can see it from [here.](https://github.com/bounswe/2021SpringGroup7/blob/master/deliverables/CM1-Group7.pdf)
