### ISSUE TITLE
CF-9 Create Profile Page

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#318]
We should create a profile page with:
- Information fields
- Editing option button
- Users own posts

**Comment by mrabiabrn** [comment]
Related Requirements : 
- **1.1.1.2** Users shall be able to view any of their personal information (email, username and name, location, birthday if provided).
- **1.1.1.3** Users shall be able to edit any of their personal information (email, username and name, location, birthday if provided).
- **1.1.1.4** Users shall be able to see users that they follow and are followed by.

- **1.1.2.6** Users shall be able to edit their own posts.

- **1.1.2.10** Users shall be able to view users who liked or commented to their posts.

**Comment by mrabiabrn** [comment]
This issue has been handled. See Related PR for more details
