### ISSUE TITLE
[WIKI UPDATE] List of deliverables and their evaluations

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#319]
Why is this wiki update necessary, what is the problem?
--------------------------------------

As mentioned in #320, this section will summarize the list of deliverables and their evaluations

Describe the solution you'd like
--------------------------------

We will summarize it in the milestone report and update the wiki

- [x]  Requirements
- [x]  UML Software Designs
- [x]  Scenarios & Mockups
- [x]  Project Plan & RAM
- [x]  Communication Plan

**Comment by hamzaakyildiz** [comment]
I wrote an evaluation for requirements and Scenarios & Mockups

**Comment by mrabiabrn** [comment]
- Listed deliverables, their status and link
- Added evaluations for software designs, project plan & communication plan

**Comment by mrabiabrn** [comment]
It seems this section is completed. I am closing the issue.
