### ISSUE TITLE
Write Evaluation of Tools & Processes for Milestone Report

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#321]
As mentioned in #320 , there should be a section where we evaluate our tools and processes in Milestone report.
This section should consist evaluation of our
- communication channels
- development platform
- design tool for mockups
- drawing platform used for diagrams
- project management system
- development frameworks for each backend, frontend & mobile

**Comment by onurcanavci** [comment]
I completed below tools and process

- Git & Github
- Slack
- Zoom
- Google Meets
- Whatsapp
- Figma
- Lucidchart
- Project Libre
- Google Docs
- Docker
- Frontend Process
- Mobile Process

**Comment by hamzaakyildiz** [comment]
I completed process evaluation for backend process
