### ISSUE TITLE
CM-7 Add Post Card Component

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#340]
Is your proposal related to a problem?
--------------------------------------

- Add a component to components folder which is post cards
- It has props which are post informations, like functions and comment function and etc.

Describe the solution you'd like
--------------------------------

- Choose a card component from native base
- Redesign according to mock api response
- Add a page to view it works like an example

**Comment by ramazanbulut** [comment]
merged
