### ISSUE TITLE
CI/CD environment variable for test live deployment 

### ISSUE THREAD

**Issue by kocasariumut** [bounswe/2021SpringGroup7#355]
Is your proposal related to a problem?
--------------------------------------

Live and test code send to the same URL for e-mail confirmation. However, they should be separated but the problem is that the code base is same. 

Describe the solution you'd like
--------------------------------

We could add environment variables to the environment variable so that they behave differently.

**Comment by hamzaakyildiz** [comment]
It works as expected with a small change on the cloud docker file
