### ISSUE TITLE
Database tables are designed

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#367]
class Story(models.Model):
class Tag(models.Model):
class Location(models.Model):
class Report(models.Model):
class Like(models.Model):
class Comment(models.Model):
class Following(models.Model):
class Profile(models.Model):

tables for the above information is added

**Comment by hamzaakyildiz** [comment]
https://github.com/bounswe/2021SpringGroup7/issues/369. Bug is fixed by @kocasariumut

**Comment by kocasariumut** [comment]
It has been also added to the admin page.
admin.site.register(Story)
admin.site.register(Tag)
admin.site.register(Location)
admin.site.register(Report)
admin.site.register(Like)
admin.site.register(Comment)
admin.site.register(Following)
admin.site.register(Profile)
