### ISSUE TITLE
Review of the Requirements

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#43]
Reviewing the requirements page after the customer meeting.

**Comment by asi345** [comment]
I reviewed the admin requirements and the changes about stories in [Requirements](https://github.com/bounswe/2021SpringGroup7/wiki/Requirements), I think they are all fine now. But we need to do the changes since locations do not have pages for themselves anymore.

**Comment by asi345** [comment]
I fixed the sentences that were mentioning the following mechanism on location pages in [Requirements](https://github.com/bounswe/2021SpringGroup7/wiki/Requirements). Someone can review the changes and close the issue.

**Comment by mrabiabrn** [comment]
I have looked at it, now our requirements covers customer's demands. Closing the issue.
