### ISSUE TITLE
Finding a Name

### ISSUE THREAD

**Issue by kocasariumut** [bounswe/2021SpringGroup7#44]
We think that it is necessary to find a name for our website and app.

**Comment by asi345** [comment]
The current name is "Hi hi history". I think it is really good, but we are open for new ideas.

**Comment by efesabanogluu** [comment]
I couldn't find another known app called Columbus, I think it's pretty cool.

**Comment by mrabiabrn** [comment]
I really like Columbus, another idea may be LocaStory.

**Comment by ramazanbulut** [comment]
I think it could be Wander or Hang (around). There is no app with name of both of two.

**Comment by CodeBlo** [comment]
I really like Columbus too.

**Comment by asi345** [comment]
I also liked Columbus.

**Comment by onurcanavci** [comment]
We decided to put Columbus in the name of the application 🎉🎊
