### ISSUE TITLE
Create Guest Scenarios

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#46]
We should create scenarios for guests.

**Comment by asi345** [comment]
We wrote the guest scenario yesterday, by meeting on Google Meets with Umut and Onur.

**Comment by asi345** [comment]
I uploaded the scenarios,o documentation to the page [Guest Scenario](https://github.com/bounswe/2021SpringGroup7/wiki/Guest-Scenario)

**Comment by asi345** [comment]
We reviewed our scenario.
