### ISSUE TITLE
Create Admin Scenarios

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#47]
We should specify the scenario for a Admin user

**Comment by hamzaakyildiz** [comment]
Admin scenario is created and uploaded [Admin Scenario](https://github.com/bounswe/2021SpringGroup7/wiki/Admin-Scenario)

**Comment by asi345** [comment]
I reviewed it and I think it is really great. We also talked about it in the meeting so it seems to be finished.
