### ISSUE TITLE
Activity Stream Implementation

### ISSUE THREAD

**Issue by efesabanogluu** [bounswe/2021SpringGroup7#505]
We decided to count everything that causes a change in the database as an activity. We will create the functionality of keeping things that create, update and delete something in a model in a certain format and see all the activities in the backend.

**Comment by kocasariumut** [comment]
One useful link for the Django implementation could be: https://django-activity-stream.readthedocs.io/en/latest/concepts.html

**Comment by kocasariumut** [comment]
Helped to resolve some issues about activity stream. Tested and validated the system and saw it works properly. Commit: https://github.com/bounswe/2021SpringGroup7/commit/0a69d283cb82b7194424097f5c1ba2c378382439

**Comment by efesabanogluu** [comment]
it is done. Finally,  tested with Umut, it works good.
