### ISSUE TITLE
Upload Meeting #5 Notes

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#51]
Document the meeting notes and upload it to Wiki page.

**Comment by CodeBlo** [comment]
I uploaded the meeting notes. Waiting for review to closing the issue. @mrabiabrn @asi345

**Comment by asi345** [comment]
I can review it

**Comment by asi345** [comment]
There was a typo at the Details table at the start time, but i fixed it. There are no more mistakes or missing part in the [meeting documentation](https://github.com/bounswe/2021SpringGroup7/wiki/Meeting-%235-(15.04.2021)). I think we can close this issue now.
