### ISSUE TITLE
Rearrangement of Admin Requirements

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#52]
Rearranging the admin user requirements with the feedbacks of customer meeting and third week group discussion

**Comment by hamzaakyildiz** [comment]
[Admin Requirements](https://github.com/bounswe/2021SpringGroup7/wiki/Requirements/_edit#13-admin-requirements) are updated according to feedbacks.

**Comment by asi345** [comment]
I think they are more clear now. This update should do the job.
