### ISSUE TITLE
Meeting about user scenarios.

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#53]
Meeting with user scenarios group in 17.04.2021.

**Comment by mrabiabrn** [comment]
We held a meeting which we discussed and determined user scenario elements such as persona, his story, preconditions and his goals with the actions he will take to achieve his goal. Noted all of these in Google docs file.

**Comment by mrabiabrn** [comment]
Meeting has ended, closing the issue.
