### ISSUE TITLE
Mockup for Search and Recommendation for Guests

### ISSUE THREAD

**Issue by asi345** [bounswe/2021SpringGroup7#58]
We should upload our designs for guest user experience.

**Comment by asi345** [comment]
- [ ] Main Page
- [ ] Search Page
- [ ] Clicking a Post
- [ ] Recommendations
- [ ] Time Filtering
- [ ] Tags
- [ ] Map Integration

**Comment by asi345** [comment]
We should upload our mockups

**Comment by kocasariumut** [comment]
I uploaded my mockups for website side.

**Comment by asi345** [comment]
I uploaded the mockups for android side.

**Comment by onurcanavci** [comment]
For android side: https://github.com/bounswe/2021SpringGroup7/wiki/Guest-in-Android-Scenario
For website side: https://github.com/bounswe/2021SpringGroup7/wiki/Guest-in-Web-Scenario

**Comment by onurcanavci** [comment]
Also you can find our mockup templates in https://www.figma.com/file/zfyLcx8i3WbGY10M1tfha0/Login (mobile) and https://www.figma.com/file/8e7kO6RHUGDrfffJ198uaF/Untitled (website)
