### ISSUE TITLE
Determining and Drawing Sequence Diagrams

### ISSUE THREAD

**Issue by hamzaakyildiz** [bounswe/2021SpringGroup7#65]

**Comment by CodeBlo** [comment]
@hamzaakyildiz and me did our parts which are 2,7,9 and 10th sequence diagrams.

**Comment by asi345** [comment]
I wrote short descriptions to the Sequence Diagrams.

**Comment by onurcanavci** [comment]
@efesabanogluu and me did our parts which are 8,11 and 12th sequence diagrams.
