### ISSUE TITLE
Determining Key Use Cases

### ISSUE THREAD

**Issue by kocasariumut** [bounswe/2021SpringGroup7#66]
We should determine use cases in order to draw sequence diagrams.

**Comment by asi345** [comment]
They are listed in [this doc file](https://docs.google.com/document/d/16oNLsl10ADVqS2ocYAIMyGkx1VCnXUCaRbw0yw0oj1U/edit)

**Comment by CodeBlo** [comment]
Key use case is determined. Closing.
