### ISSUE TITLE
Determine Use Case Diagram Components

### ISSUE THREAD

**Issue by asi345** [bounswe/2021SpringGroup7#68]
We should decide on the components and parts of the use case diagram for each user type.

**Comment by mrabiabrn** [comment]
Use case diagrams should be ready until 24.04.21 @23.59

**Comment by mrabiabrn** [comment]
Use case diagram is in review. Everyone should check it from the link in Slack.

**Comment by asi345** [comment]
I think we should take look at the labels of the arrows. We used a lot of "extends" label but Umut said some of them should be considered as generalization.

**Comment by kocasariumut** [comment]
We will ask some questions about this to TA.

**Comment by asi345** [comment]
~ Is [Use Case Diagram](https://github.com/bounswe/2021SpringGroup7/wiki/Use-Case-Diagram) finished?
- Yes
~ What did it cost?
- Everything
