### ISSUE TITLE
Creating Lucidchart teams

### ISSUE THREAD

**Issue by CodeBlo** [bounswe/2021SpringGroup7#69]
Creating a Lucidchart teams for creating the diagrams.

**Comment by CodeBlo** [comment]
Created a Lucidchart team for Class diagrams. Can be viewed [here](https://lucid.app/lucidchart/invitations/accept/inv_9a22683e-7765-440b-8343-70c96ec3e853).

**Comment by hamzaakyildiz** [comment]
[USE CASE DIAGRAM](https://lucid.app/lucidchart/invitations/accept/inv_17f013ec-ffd6-4d49-87fa-943874209c75?viewport_loc=-11%2C-11%2C1424%2C773%2C0_0) is created.

**Comment by CodeBlo** [comment]
Created a Lucidchart team for Sequence Diagrams. [Link](https://lucid.app/lucidchart/invitations/accept/inv_30dcbbac-2d18-4ed5-acf4-a9b94ef4038a?viewport_loc=-3249%2C-1789%2C7098%2C4046%2C0_0)

**Comment by CodeBlo** [comment]
All teams are created. Closing the issue

**Comment by CodeBlo** [comment]
All teams are created. Closing the issue.
