### ISSUE TITLE
Summarizing Github Repository Research

### ISSUE THREAD

**Issue by kocasariumut** [bounswe/2021SpringGroup7#7]
Some repositories should be investigated to get better ideas about how github works

- [x] [Abdulkadir Elmacı](https://github.com/bounswe/2021SpringGroup7/wiki/Abdulkadir-Elmacı)
- [x] [Efe Şabanoğlu]()
- [x] [Erencan Uysal](https://github.com/bounswe/2021SpringGroup7/wiki/Erencan-Uysal)
- [x] [Hamza Akyıldız](https://github.com/bounswe/2021SpringGroup7/wiki/Hamza-Akyıldız)
- [x] [İsmail Ata İnan](https://github.com/bounswe/2021SpringGroup7/wiki/İsmail-Ata-İnan)
- [x] [Merve Rabia Barın](https://github.com/bounswe/2021SpringGroup7/wiki/Merve-Rabia-Barın)
- [x] [Onur Can Avcı](https://github.com/bounswe/2021SpringGroup7/wiki/Onur-Can-Avcı)
- [x] [Ramazan Bulut](https://github.com/bounswe/2021SpringGroup7/wiki/Ramazan-Bulut)
- [x] [Umut Kocasarı](https://github.com/bounswe/2021SpringGroup7/wiki/Umut-Kocasarı)

**Comment by onurcanavci** [comment]
Github Project Management: https://github.com/features/project-management/

**Comment by CodeBlo** [comment]
Some of the GitHub projects that I like:
* https://github.com/flutter/flutter
* https://github.com/sbraconnier/jodconverter
* https://github.com/bytedeco/javacpp

**Comment by asi345** [comment]
I really liked the repository https://github.com/beetbox/beets.
I wrote an introductory summary of the repository with some of its features in [Favorite Github Repositories](https://github.com/bounswe/2021SpringGroup7/wiki/Favorite-Github-Repositories).

**Comment by kocasariumut** [comment]
I wrote Hugging Face as my favorite repository: https://github.com/huggingface/transformers

**Comment by CodeBlo** [comment]
> Some of the GitHub projects that I like:
> 
> * https://github.com/flutter/flutter
> * https://github.com/sbraconnier/jodconverter
> * https://github.com/bytedeco/javacpp

I also wrote about the mentioned repositories.

**Comment by erencanuysal** [comment]
I added https://github.com/danistefanovic/build-your-own-x as my favorite repository.

**Comment by hamzaakyildiz** [comment]
I added https://github.com/iperov/DeepFaceLab as my favorite repository

**Comment by efesabanogluu** [comment]
I started learning .net since I started a new job. Thanks to this, I had the chance to examine the .net's repository and I can say that it is quite interesting.
