### ISSUE TITLE
Upload Sequence Diagrams to Wiki

### ISSUE THREAD

**Issue by asi345** [bounswe/2021SpringGroup7#72]
We should upload to final version of Sequence Diagrams to Wiki

**Comment by asi345** [comment]
The wiki page can be accessed by [this link](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams)

**Comment by CodeBlo** [comment]
Uploaded currently available diagrams to GitHub.(1,2,3,4,5,6,7,9,10)

**Comment by efesabanogluu** [comment]
Diagrams 8,11 and 12 are current avaliable on [Sequence Diagrams' page](https://github.com/bounswe/2021SpringGroup7/wiki/Sequence-Diagrams). All sequences are over.
