### ISSUE TITLE
Writing Executive Summary for the Final Milestone Report

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#731]
We should write an Executive summary containing:
- Status of deliverables.
- Status of all requirements. Status values: Completed, Not completed. Completed means implemented, tested, documented, and deployed.
- Final release notes.
- Describe the changes your team has planned/implemented to improve the
development process based on previous milestone reflections and how they
impacted your process.
- Final project evaluations: Reflections related to your Final Milestone Demo
including lessons learned.

**Comment by CodeBlo** [comment]
We wrote the executive summary with @erencanuysal.
