### ISSUE TITLE
Review and update requirements

### ISSUE THREAD

**Issue by erencanuysal** [bounswe/2021SpringGroup7#76]
Review and update requirements according to changes on scenarios and use cases.

**Comment by hamzaakyildiz** [comment]
Check the possible updates on the requirements, the link are available on WhatsApp.

**Comment by mrabiabrn** [comment]
We discussed **1.1.6 Communication** & decided that it is not essential for our project in this stage. We should focus on the main purpose of sharing location stories wtih other people.

**Comment by hamzaakyildiz** [comment]
Requirements are updated
