### ISSUE TITLE
Preparing communication plan

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#8]
Provide participant, location, purpose and date info in communication plan.

**Comment by mrabiabrn** [comment]
@hamzaakyildiz there is a typo in "When" column's first row, can you fix it?

**Comment by hamzaakyildiz** [comment]
Fixed it. Thank you.

**Comment by hamzaakyildiz** [comment]
Communication Plan is prepared according to our current communication requirements. It will be updated whenever needed.
