### ISSUE TITLE
Writing Future Plan for 352

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#92]
Decide tasks by looking at the curriculum of the course

**Comment by asi345** [comment]
The future plans for CMPE 352 are ready in Google Doc, it is waiting for review.

**Comment by asi345** [comment]
The future plans are ready on our [milestone report](https://github.com/bounswe/2021SpringGroup7/blob/master/deliverables/M1-Group7.pdf)
