### ISSUE TITLE
Writing future plan for the Mobile/Web (Frontend)

### ISSUE THREAD

**Issue by mrabiabrn** [bounswe/2021SpringGroup7#93]
Determine the plan for the Mobile/Web (Frontend) parts of the project.

**Comment by onurcanavci** [comment]
We add Frontend Plans to [Future Plan File](https://docs.google.com/spreadsheets/d/12a2yEfgEtWQgUINOZwDpsaZRNqcVJNsTFK0EU3Sto1g/edit#gid=1044589596)

**Comment by asi345** [comment]
All future plans are ready in [project plan](https://github.com/bounswe/2021SpringGroup7/wiki/Project-Plan)
