### ISSUE TITLE
Researching and Creating GitHub Projects 

### ISSUE THREAD

**Issue by onurcanavci** [bounswe/2021SpringGroup7#96]
Researching how to use github projects and how to integrate to our projects

**Comment by onurcanavci** [comment]
We find create issue branch app for github and we're trying how to import our project
https://github.com/marketplace/actions/create-issue-branch#:~:text=A%20GitHub%20App%2FAction%20that,-branch%20or%20%2Fcib%20

**Comment by CodeBlo** [comment]
Onur Can created the projects. Seems good. Closing.
